const DEMO_ISSUES = [
  { id: 'demo-1', category: 'Air Quality', title: 'Elevated particulate readings', description: 'PM2.5 readings are above the watch threshold near the industrial corridor.', location: 'Ironworks District', severity: 'Critical', status: 'In Progress', created_at: '2026-09-24T09:24:00Z', latitude: 42.365, longitude: -71.055 },
  { id: 'demo-2', category: 'Water', title: 'Low pressure reported', description: 'Residents report intermittent pressure on the east mains.', location: 'Waterfront East', severity: 'High', status: 'Acknowledged', created_at: '2026-09-24T08:12:00Z', latitude: 42.354, longitude: -71.045 },
  { id: 'demo-3', category: 'Sanitation/Waste', title: 'Missed collection route', description: 'Collection has not arrived for the scheduled morning route.', location: 'Central Civic Center', severity: 'Medium', status: 'Reported', created_at: '2026-09-24T07:45:00Z', latitude: 42.361, longitude: -71.063 },
  { id: 'demo-4', category: 'Traffic', title: 'Signal outage at 4th and Main', description: 'Traffic signal is flashing and creating delays during the morning peak.', location: 'Mid-Town Spine', severity: 'High', status: 'Resolved', created_at: '2026-09-23T17:20:00Z', latitude: 42.372, longitude: -71.071 }
];
const CATEGORIES = ['Water', 'Sanitation/Waste', 'Healthcare', 'Air Quality', 'Traffic'];
let issues = [...DEMO_ISSUES];
let supabaseClient = null;
const telemetryState = { aqi: null, traffic: null };
const telemetryIntervals = { aqi: 5 * 60 * 1000, traffic: 60 * 1000 };

function reading(payload, metric) { return payload?.readings?.find(item => item.metric_id === metric); }
function telemetryTime(payload) { const values = payload?.readings?.map(item => Date.parse(item.timestamp_utc)).filter(Number.isFinite) || []; return values.length ? Math.max(...values) : 0; }
function telemetryIsStale(payload, kind) { const timestamp = telemetryTime(payload); return Boolean(payload?.stale || !timestamp || Date.now() - timestamp > telemetryIntervals[kind] * 2); }
function telemetryStatus(payload, kind) { return telemetryIsStale(payload, kind) ? '<span class="badge badge-demo stale">STALE DATA</span>' : '<span class="badge">LIVE</span>'; }
function formatUpdated(payload) { const timestamp = telemetryTime(payload); return timestamp ? `Updated ${formatTime(timestamp)}` : 'No reading'; }
function aqiBand(value) { if (value === null || value === undefined) return ['Unavailable', '']; if (value <= 50) return ['Good', 'band-good']; if (value <= 100) return ['Moderate', 'band-moderate']; if (value <= 150) return ['Unhealthy for sensitive groups', 'band-unhealthy']; if (value <= 200) return ['Unhealthy', 'band-unhealthy']; if (value <= 300) return ['Very unhealthy', 'band-unhealthy']; return ['Hazardous', 'band-unhealthy']; }
function renderTelemetry(kind, payload, error = '') {
  const isAqi = kind === 'aqi';
  const content = document.querySelector(`#${kind}-content`);
  const updated = document.querySelector(`#${kind}-updated`);
  const message = document.querySelector(`#${kind}-message`);
  if (!payload?.readings?.length) { content.className = 'telemetry-message error-text'; content.textContent = error || 'No live readings available.'; updated.innerHTML = telemetryStatus(payload, kind); message.textContent = 'Configure server credentials or wait for the upstream service.'; return; }
  const aqi = reading(payload, 'aqi');
  if (isAqi) {
    const [label, bandClass] = aqiBand(aqi?.value);
    const badge = document.querySelector('#aqi-band'); badge.textContent = label; badge.className = `badge ${bandClass}`;
    content.className = 'telemetry-values'; content.innerHTML = `<div class="telemetry-value"><small>AQI</small><strong>${aqi?.value ?? '—'}</strong></div><div class="telemetry-value"><small>PM2.5</small><strong>${reading(payload, 'pm2.5')?.value ?? '—'}</strong><small>µg/m³</small></div><div class="telemetry-value"><small>PM10</small><strong>${reading(payload, 'pm10')?.value ?? '—'}</strong><small>µg/m³</small></div>`;
  } else {
    const congestion = reading(payload, 'congestion_percent'); const speed = reading(payload, 'current_speed'); const freeFlow = reading(payload, 'free_flow_speed'); const incidents = reading(payload, 'incident_count');
    content.className = 'telemetry-values'; content.innerHTML = `<div class="telemetry-value"><small>Congestion</small><strong>${congestion ? Math.max(0, Math.round(100 - congestion.value)) : '—'}%</strong><div class="traffic-meter"><span style="width:${congestion ? Math.min(100, Math.max(0, 100 - congestion.value)) : 0}%"></span></div></div><div class="telemetry-value"><small>Speed / free flow</small><strong>${speed?.value ?? '—'} <small>/ ${freeFlow?.value ?? '—'} km/h</small></strong></div><div class="telemetry-value"><small>Incidents</small><strong>${incidents?.value ?? '—'}</strong></div>`;
    const overlay = document.querySelector('#traffic-overlay'); if (overlay) overlay.textContent = congestion ? `Traffic layer: ${Math.max(0, Math.round(100 - congestion.value))}% congested` : 'Traffic layer: unavailable';
  }
  updated.innerHTML = `${telemetryStatus(payload, kind)} <span class="muted">${formatUpdated(payload)}</span>`;
  message.textContent = error ? `Using cached data: ${error}` : `Source: ${payload.source || 'configured provider'}`;
  message.className = `telemetry-message ${error || telemetryIsStale(payload, kind) ? 'stale' : 'muted'}`;
}
async function fetchTelemetry(kind) { try { const response = await fetch(`/api/${kind}`, { cache: 'no-store' }); const payload = await response.json(); const nextTimestamp = telemetryTime(payload); if (!telemetryState[kind] || nextTimestamp !== telemetryTime(telemetryState[kind]) || payload.stale !== telemetryState[kind].stale) { telemetryState[kind] = payload; renderTelemetry(kind, payload, payload.error); } } catch (error) { renderTelemetry(kind, telemetryState[kind], error.message); } }
function connectTelemetryStream() { if (!window.EventSource) return; let stream; const open = () => { if (document.hidden) return; stream = new EventSource('/api/stream'); stream.onmessage = event => { const payload = JSON.parse(event.data); ['aqi', 'traffic'].forEach(kind => { if (payload[kind]) { telemetryState[kind] = payload[kind]; renderTelemetry(kind, payload[kind], payload[kind].error); } }); }; stream.onerror = () => stream.close(); }; document.addEventListener('visibilitychange', () => { if (document.hidden) stream?.close(); else { fetchTelemetry('aqi'); fetchTelemetry('traffic'); open(); } }); open(); }
function loadTelemetry() { fetchTelemetry('aqi'); fetchTelemetry('traffic'); connectTelemetryStream(); }

function formatTime(value) { return new Intl.RelativeTimeFormat('en', { numeric: 'auto' }).format(Math.round((new Date(value) - Date.now()) / 60000), 'minute'); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function selectedIssues() { const category = document.querySelector('#category-filter').value; const severity = document.querySelector('#severity-filter').value; const status = document.querySelector('#status-filter').value; const location = document.querySelector('#location-filter').value.toLowerCase(); return issues.filter(issue => (!category || issue.category === category) && (!severity || issue.severity === severity) && (!status || issue.status === status) && (!location || issue.location.toLowerCase().includes(location))); }
function renderCategories() { document.querySelector('#category-cards').innerHTML = CATEGORIES.map(category => { const count = issues.filter(issue => issue.category === category && issue.status !== 'Resolved').length; const names = { Water: 'Water systems', 'Sanitation/Waste': 'Sanitation / waste', Healthcare: 'Healthcare access', 'Air Quality': 'Air quality', Traffic: 'Traffic flow' }; return `<article class="metric"><span class="eyebrow">${names[category]}</span><strong>${count}</strong><span class="metric-meta">open issues / live signal</span></article>`; }).join(''); }
function renderIssues() { const filtered = selectedIssues(); document.querySelector('#issue-count').textContent = `${filtered.length} visible`; document.querySelector('#issue-list').innerHTML = filtered.length ? filtered.map(issue => `<article class="issue"><div class="issue-top"><span class="issue-title">${escapeHtml(issue.title)}</span><span class="status">${escapeHtml(issue.status)}</span></div><p class="issue-description">${escapeHtml(issue.description)}</p><div class="issue-foot"><span>${escapeHtml(issue.category)} · ${escapeHtml(issue.location)}</span><span class="severity">${escapeHtml(issue.severity)} · ${formatTime(issue.created_at)}</span></div></article>`).join('') : '<p class="muted">No issues match these filters.</p>'; }
function renderCharts() { const days = [3, 5, 4, 8, 6, 9, issues.length + 4]; document.querySelector('#trend-chart').innerHTML = days.map((value, index) => `<div class="bar" style="height:${value * 11}px"><span>${['M','T','W','T','F','S','Today'][index]}</span></div>`).join(''); document.querySelector('#category-chart').innerHTML = CATEGORIES.map(category => { const count = issues.filter(issue => issue.category === category).length; return `<div class="cat-row"><span>${category}</span><span class="cat-fill" style="width:${Math.max(8, count / issues.length * 100)}%"></span><strong>${count}</strong></div>`; }).join(''); }
function renderMap() { const category = document.querySelector('#map-category-filter').value; const severity = document.querySelector('#map-severity-filter').value; const visible = issues.filter(issue => issue.latitude && (!category || issue.category === category) && (!severity || issue.severity === severity)); document.querySelector('#issue-map').querySelectorAll('.map-marker').forEach(marker => marker.remove()); visible.forEach(issue => { const marker = document.createElement('button'); marker.className = `map-marker ${issue.severity.toLowerCase()}`; marker.title = `${issue.title} - ${issue.location}`; marker.style.left = `${((issue.longitude + 71.09) / .06) * 100}%`; marker.style.top = `${((42.39 - issue.latitude) / .05) * 100}%`; marker.addEventListener('click', () => alert(`${issue.title}\n${issue.location}\n${issue.status}`)); document.querySelector('#issue-map').append(marker); }); }
function render() { renderCategories(); renderIssues(); renderCharts(); renderMap(); }
function populateSelects() { ['#category-filter', '#map-category-filter'].forEach(selector => CATEGORIES.forEach(category => document.querySelector(selector).insertAdjacentHTML('beforeend', `<option>${category}</option>`))); }
async function loadIssues() { const url = window.CITYPULSE_SUPABASE_URL; const key = window.CITYPULSE_SUPABASE_ANON_KEY; const configured = typeof url === 'string' && /^https?:\/\//.test(url) && key && !key.startsWith('YOUR_'); if (!configured || !window.supabase) return; supabaseClient = window.supabase.createClient(url, key); const { data, error } = await supabaseClient.from('civic_issues').select('*').order('created_at', { ascending: false }); if (!error && data) { issues = data; document.querySelector('#data-mode').textContent = 'SUPABASE LIVE'; document.querySelector('#data-mode').className = 'badge'; document.querySelector('#connection-state').textContent = 'Realtime ready'; supabaseClient.channel('civic-issues').on('postgres_changes', { event: '*', schema: 'public', table: 'civic_issues' }, payload => { if (payload.eventType === 'INSERT') issues.unshift(payload.new); if (payload.eventType === 'UPDATE') issues = issues.map(issue => issue.id === payload.new.id ? payload.new : issue); if (payload.eventType === 'DELETE') issues = issues.filter(issue => issue.id !== payload.old.id); render(); }).subscribe(); render(); } }
async function submitIssue(form) { const issue = { category: form.category.value, title: form.title.value, description: form.description.value, location: form.location.value, severity: form.severity.value, status: 'Reported', created_at: new Date().toISOString() }; if (supabaseClient) { const { data, error } = await supabaseClient.from('civic_issues').insert(issue).select().single(); if (error) return alert(error.message); issues.unshift(data); } else { issues.unshift({ ...issue, id: `local-${Date.now()}` }); } form.reset(); document.querySelector('#report-dialog').close(); render(); }
document.addEventListener('DOMContentLoaded', () => { populateSelects(); render(); loadIssues(); loadTelemetry(); document.querySelectorAll('select,input').forEach(input => input.addEventListener('input', render)); document.querySelectorAll('select').forEach(input => input.addEventListener('change', render)); const dialog = document.querySelector('#report-dialog'); document.querySelector('#report-open').onclick = () => dialog.showModal(); document.querySelector('#report-close').onclick = () => dialog.close(); document.querySelector('#report-cancel').onclick = () => dialog.close(); document.querySelector('#report-form').addEventListener('submit', event => { event.preventDefault(); submitIssue(event.currentTarget); }); });
